let nome = prompt("Digite o seu nome")
let sobrenome = prompt("Digite o seu sobrenome")
let anoNascimento = prompt("Digite o ano em que você nasceu")
let cidade = prompt("Digite a cidade em que você mora")
let estado = prompt("Digite o Estado")
let ano = prompt ("Digite em que ano você está falando")
let idade = (ano) - (anoNascimento)

console.log(`Olá, me chamo ${nome} ${sobrenome}, tenho ${idade} anos e moro em ${cidade} / ${estado} `)
alert(`Olá, me chamo ${nome} ${sobrenome}, tenho ${idade} anos e moro em ${cidade} / ${estado} `)
